config/routes.rb
Rails.application.routes.draw do
  root 'coins#index'
  get '/project', to: 'statics#project'
  get '/team', to: 'statics#team'

  devise_for :users
  resources :selections
  resources :coins, only: [:show]
  resources :users, only: [:show, :edit, :update]

  namespace :admin do
    root "users#index"
    resources :users
    resources :coins
    resources :values
  end
end

app/models/user.rb
class User < ApplicationRecord
    has_many :selections
    has_many :coins, through: :selections

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  after_create :welcome_send
  
  def welcome_send
    puts 'sending welcome mail...'
    UserMailer.welcome_email(self).deliver_now!
  end

  def admin?
    return self.admin==true
  end

  def already_liked(coin_id)
    return self.coins.include?(Coin.find_by(id:coin_id))
  end

end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  
  def show
    @user = current_user
  end

  def edit
    @user = current_user
  end
  
  def update
    @user = current_user
    if @user.update(user_params)
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/edit.html.erb
<% provide(:title,  " | Profil" ) %>

<div class="max-w-xl bg-white shadow-md rounded px-8 pt-6 pb-8 mt-6 mx-auto">

<!-- FORM -->
<%= form_for(current_user, url: user_path(current_user), method: :put) do |f| %>

  <p class="text-center text-gray-700 text-lg font-bold mb-8">MODIFIER MES INFORMATIONS</p>

  <div class="flex mb-10">
    <div class="w-2/4">
      <%= f.label :Prénom, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= f.text_field :first_name, autocomplete: :first_name, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:border-green-300 outline-none", placeholder: "#{
        if @user.first_name.nil?
          "John"
        else
          @user.first_name
        end
      }" %>
    </div>
    <div class="mx-2"></div>
    <div class="w-2/4">
      <%= f.label :Nom, class: "block text-gray-700 text-sm font-bold mb-2" %>
      <%= f.text_field :last_name, autocomplete: :last_name, class: "shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:border-green-300 outline-none", placeholder: "#{
        if @user.last_name.nil?
          "Doe"
        else
          @user.last_name
        end
      }" %>
    </div>
  </div>

  <!-- BUTTONS -->
  <div class="flex justify-center">
    <%= f.submit "Valider", class: "bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded border-none outline-none" %>
    <%= link_to "Retour", :back, class: "bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 ml-2 rounded border-none outline-none" %>
  </div>
  <!-- BUTTONS -->

<% end %>
<!-- FORM -->

</div>

app/views/users/show.html.erb
<% provide(:title,  " | Profil" ) %>

<div class="max-w-xl bg-white shadow-md rounded px-8 pt-6 pb-8 mt-6 mx-auto">

<p class="text-center text-gray-700 text-lg font-bold mb-6">MON PROFIL</p>

<div class="text-gray-600 my-5">
  <div class="flex justify-center text-3xl mb-3">
    <% if @user.first_name.nil? %>
      <p class="italic">Prénom</p>
    <% else %>
      <p><%= @user.first_name %></p>
    <% end %>
    <div class="mx-2"></div>
    <% if @user.last_name.nil? %>
      <p class="italic">Nom</p>
    <% else %>
      <p><%= @user.last_name %></p>
    <% end %>
  </div>
  <p class="text-center text-xl mb-10"><%= @user.email %></p>
</div>

<!-- BUTTONS -->
<div class="flex justify-center">
  <%= link_to "Informations", edit_user_path, class: "bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 rounded border-none outline-none" %>
  <%= link_to "Compte", edit_user_registration_path, class: "bg-green-500 hover:bg-green-700 text-white font-bold py-2 px-4 ml-2 rounded border-none outline-none" %>
  <%= link_to "Retour", :back, class: "bg-gray-500 hover:bg-gray-700 text-white font-bold py-2 px-4 ml-2 rounded border-none outline-none" %>
</div>
<!-- BUTTONS -->

</div>