config/routes.rb
Rails.application.routes.draw do
  root 'coins#index'
  get '/project', to: 'statics#project'
  get '/team', to: 'statics#team'

  devise_for :users
  resources :selections
  resources :coins, only: [:show]
  resources :users, only: [:show, :edit, :update]

  namespace :admin do
    root "users#index"
    resources :users
    resources :coins
    resources :values
  end
end

app/models/coin.rb
class Coin < ApplicationRecord
    has_many :selections
    has_many :users, through: :selections

    #Coin's values can change, depends on interval (daily ,hourly,...)
    has_many :values

    validates :symbol, uniqueness:true, presence:true
    validates :name, uniqueness:true, presence:true

    def minutely
      array = []
      values.each{ |index|
          if(index.minutely?)
              array << index
          end
      }
      return array 
    end

    def daily
      array = []
      values.each{ |index|
          if(index.daily?)
              array << index
          end
      }
      return array
    end

    def hourly
        array = []
        values.each{ |index|
            if(index.hourly?)
                array << index
            end
        }
        return array 
    end

    def has_interval_values?(interval)
      case interval
        when 'daily'
          self.values.daily.any?
        when 'hourly'
          self.values.hourly.any?
        end
    end

    #Translate Coin Values to USD price
    include ActionView::Helpers::NumberHelper

    def last_price
      number_to_currency(self.values.hourly.last.price, :unit => "$ ", :delimiter => ",", :separator => ".")
    end
    
    def last_volume
      number_to_currency(self.values.hourly.last.volume, :unit => "$ ", :delimiter => ",", :precision => 0)
    end

    def last_market_cap
      number_to_currency(self.values.hourly.last.market_cap, :unit => "$ ", :delimiter => ",", :precision => 0)
    end
end

app/controllers/admin/coins_controller.rb
module Admin
  class CoinsController < Admin::ApplicationController
    # Overwrite any of the RESTful controller actions to implement custom behavior
    # For example, you may want to send an email after a foo is updated.
    #
    # def update
    #   super
    #   send_foo_updated_email(requested_resource)
    # end

    # Override this method to specify custom lookup behavior.
    # This will be used to set the resource for the `show`, `edit`, and `update`
    # actions.
    #
    # def find_resource(param)
    #   Foo.find_by!(slug: param)
    # end

    # The result of this lookup will be available as `requested_resource`

    # Override this if you have certain roles that require a subset
    # this will be used to set the records shown on the `index` action.
    #
    # def scoped_resource
    #   if current_user.super_admin?
    #     resource_class
    #   else
    #     resource_class.with_less_stuff
    #   end
    # end

    # Override `resource_params` if you want to transform the submitted
    # data before it's persisted. For example, the following would turn all
    # empty values into nil values. It uses other APIs such as `resource_class`
    # and `dashboard`:
    #
    # def resource_params
    #   params.require(resource_class.model_name.param_key).
    #     permit(dashboard.permitted_attributes).
    #     transform_values { |value| value == "" ? nil : value }
    # end

    # See https://administrate-prototype.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/coins_controller.rb
class CoinsController < ApplicationController
  def index
    @coins = Coin.all
    if current_user
      @selections = current_user.coins
    end
  end

  def show
    @coin = Coin.find(params[:id])
    @values = @coin.values
  end
end

app/helpers/coins_helper.rb
module CoinsHelper
end

app/views/coins/index.html.erb
<% unless user_signed_in? %>
<!-- VISITORS HEADER -->
  <div class="py-10 bg-green-600 z-30">
    <div class="container text-gray-200 px-3 mx-auto flex flex-wrap flex-col md:flex-row items-center">
      <div class="flex flex-col w-full md:w-2/5 justify-center items-center text-center md:text-left">
        <h1 class="my-4 text-5xl font-bold uppercase text-center leading-tight">
          Le comparateur de cryptomonnaies facile d'accès
        </h1>
        <p class="leading-normal text-xl font-light text-center mb-8">
          Blockchain, tokens, trading... les cryptos au début c'est compliqué, mais ça vient de changer. Avec Pilea, que tu sois juste curieux ou déjà un maître de la blockchain, toutes les infos dont tu as besoin sont ici. Tu peux comparer les données des plus importantes cryptos du marché très simplement, fini de se prendre la tête !
        </p>
        <p class="uppercase tracking-loose font-bold text-center w-full">
          Service entièrement libre et gratuit
        </p>
        <%= link_to button_tag("REJOINDRE L'AVENTURE", class: "mx-auto uppercase shadow-lg hover:shadow-3xl bg-gray-200 text-green-500 hover:text-green-700 font-bold text-xl rounded-full z-40 my-6 py-4 px-32 shadow-lg"), new_user_registration_path %>
      </div>

      <div class="w-full md:w-3/5 pb-16 pt-6 flex justify-center text-center">
        <%= image_tag(('hero.png'), class: "w-3/5 h-3/5 mx-auto relative z-40") %>
      </div>
    </div>
  </div>
<!-- VISITORS HEADER -->
<% end %>

<%= render 'assets/transition' %>

<!-- ALL COINS DATATABLE -->
<div class="w-full bg-white tracking-wider z-10 leading-normal">

  <div class="p-6">
    
    <table id="table_coins" class="display responsive no-wrap mx-auto">
      <thead>
        <tr class="text-gray-700">
          <th>Nom</th>
          <th data-priority="1">Évolution Prix</th>
          <th>Prix</th>
          <th>Volume</th>
          <th>Capitalisation</th>
          <th data-priority="1"></th>
        </tr>
      </thead>
      <tbody>				
        <% @coins.each do |coin| %>
          <tr class="uppercase text-center">
            <td>
              <%= link_to image_tag((coin.logo), class: "w-5 h-5 lg:w-10 lg:h-10 lg:-mb-6 mr-2 rounded-full"), coin_path(coin) %>
              <%= link_to coin.name, coin_path(coin) %>
            </td class="flex justify-center">
            <td class="chart-container">
              <canvas id="coins-chart-<%= coin.name %>" width="40" height="15"></canvas>
            </td>
            <td>
              <%= link_to coin.last_price, coin_path(coin), class: "flex justify-center" %>
            </td>
            <td>
              <%= link_to coin.last_volume, coin_path(coin), class: "flex justify-center" %>
            </td>
            <td>
              <%= link_to coin.last_market_cap, coin_path(coin), class: "flex justify-center" %>
            </td>
            <td id="likebutton<%=coin.id %>">
              <% if current_user %>
                <% if current_user.already_liked(coin) %>
                  <%= link_to image_tag(('unlike.png'), class: "w-5 h-5 lg:w-8 lg:h-8"), selection_path(id: coin), method: :delete, remote:true %>
                <% else %>
                  <%= link_to image_tag(('like.png'), class: "w-5 h-5 lg:w-8 lg:h-8"), selections_path(id: coin), method: :post, remote:true %>
                <% end %>
              <% else %>
                <%= link_to image_tag(('like.png'), class: "w-5 h-5 lg:w-8 lg:h-8"), new_user_registration_path %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>
<div id="coins-index"></div>
<!-- ALL COINS DATATABLE -->

<%= javascript_include_tag 'table_coins' %>
<%= render 'assets/charts_coins.js.erb' %>

app/views/coins/show.html.erb
<% provide(:title, " | #{@coin.name.capitalize}") %>

<div class="bg-gray-200 shadow-2xl rounded-lg mx-auto mt-6 mb-4 px-12 py-4 w-10/12">
  <!-- COIN HEADER -->
  <div class="w-full mx-auto block flex-grow text-gray-700 border-gray-300 border-b-2 lg:flex lg:items-center lg:justify-between">
    <div class="block sm:my-8 flex justify-center">
      <%= link_to image_tag((@coin.logo), class: "w-16 h-16 rounded-full object-cover my-auto shadow-2xl"), root_path %>
      <%= link_to @coin.name, root_path, class: "w-16 my-auto text-lg uppercase font-bold ml-3 text-center" %>
    </div>
    <div class="block lg:inline-block sm:my-8 flex justify-center">
      <p class="my-auto sm:mx-8 text-sm tracking-widest text-center">
        PRIX

      </p>
      <p class="my-auto text-2xl font-medium text-center">
        <%= link_to @coin.last_price %>
      </p>
    </div>
    <div class="block lg:inline-block sm:my-8 flex justify-center">
      <p class="my-auto sm:mx-8 text-sm tracking-widest text-center">
        VOLUME
      </p>
      <p class="my-auto text-2xl font-medium text-center">
        <%= link_to @coin.last_volume %>
      </p>
    </div>
    <div class="block lg:inline-block sm:my-8 flex justify-center">
      <p class="my-auto sm:mx-8 text-sm tracking-widest text-center">
        CAPITALISATION
      </p>
      <p class="my-auto text-2xl font-medium text-center">
        <%= link_to @coin.last_market_cap %>
      </p>
    </div>
    <div id="likebutton<%=@coin.id %>" class="flex justify-center">
      <% if current_user %>
        <% if current_user.already_liked(@coin) %>
          <%= link_to image_tag(('unlike.png'), class: "w-5 h-5 lg:w-8 lg:h-8"), selection_path(id: @coin), method: :delete, remote:true %>
        <% else %>
          <%= link_to image_tag(('like.png'), class: "w-5 h-5 lg:w-8 lg:h-8"), selections_path(id: @coin), method: :post, remote:true %>
        <% end %>
      <% else %>
        <%= link_to image_tag(('like.png'), class: "w-5 h-5 lg:w-8 lg:h-8"), new_user_registration_path %>
      <% end %>
      </div>
  </div>
  <!-- COIN HEADER -->

  <!-- COIN DATATABLE -->
  <div class="w-full mb-5 mt-3 lg:justify-between sm:justify-center">
    <div class="flex flex-wrap">
      <div class="chart-container w-2/4 relative rounded-lg p-5">
        <canvas id="today-line-<%= @coin.name %>" width="550" height="300"></canvas>
      </div>
      <div class="chart-container w-2/4 relative rounded-lg p-5">
        <canvas id="today-bar-<%= @coin.name %>" width="550" height="300"></canvas>
      </div>
    </div>
    <div class="flex flex-wrap">
      <div class="chart-container w-2/4 relative rounded-lg p-5">
        <canvas id="week-line-<%= @coin.name %>" width="550" height="300"></canvas>
      </div>
      <div class="chart-container w-2/4 relative rounded-lg p-5">
        <canvas id="week-bar-<%= @coin.name %>" width="550" height="300"></canvas>
      </div>
    </div>
    </div>
    <div class="flex flex-wrap">
      <div class="chart-container w-2/4 relative rounded-lg p-5">
        <canvas id="year-line-<%= @coin.name %>" width="550" height="300"></canvas>
      </div>
      <div class="chart-container w-2/4 relative rounded-lg p-5">
        <canvas id="year-bar-<%= @coin.name %>" width="550" height="300"></canvas>
      </div>
    </div>
    <div class="chart-container relative rounded-lg p-5 mx-auto">
      <canvas id="forever-line-<%= @coin.name %>" width="1000" height="500"></canvas>
    </div>
    <!-- COIN DATATABLE -->
</div>

<script>
  <%= render 'assets/charts_coin.js' %>
</script>